In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [12]:
df = pd.read_csv("/Users/darshgupta/Desktop/Winter Sem/IOT Domain Analyst/LAB/Task 2/Dataset2.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [13]:
df.bedrooms.median()

4.0

In [14]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [16]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('price',axis='columns'),df.price)

LinearRegression()

In [17]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [18]:
reg.intercept_

221323.00186540425

### price of home with 3000 sqr ft area, 3 bedrooms, 40-year-old

In [19]:
reg.predict([[3000, 3, 40]])

/Users/darshgupta/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

### price of home with 4800 sqr ft area, 3 bedrooms, 35 years old

In [21]:
reg.predict([[4800, 3, 35]])

/Users/darshgupta/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([716279.23661931])